"use client";

/**
 * The repayment plan as a document — the thing that comes out of "Download repayment
 * plan".
 *
 * It is rendered into the page and hidden until print, rather than generated by a PDF
 * library. `jspdf` plus a font that can draw Devanagari is ~300KB to produce a worse
 * document than the browser already makes for free, and this app has a 200KB budget on
 * the citizen route and assumes a ₹6,000 phone on 2G. Chrome on Android prints to PDF
 * from the same dialog as everything else, so the citizen gets a real file and the bundle
 * pays nothing. That trade is why `window.print()` was already the export on this page
 * before the design drop asked for a download button.
 *
 * Two consequences worth knowing:
 *
 *   - Amounts print as "Rs" and not "₹". The reference PDF renders the rupee sign as a
 *     superscript "1" because its embedded font has no glyph for it, and that is exactly
 *     the failure to avoid on a page of money. "Rs" is the rule pack's own house style —
 *     `micro_finance.yaml` writes "Rs 5,00,000" — so the document matches its source.
 *   - `print-color-adjust: exact` is set on the header bands. Without it browsers drop
 *     background colours when printing and the navy header comes out as white space with
 *     white text in it.
 */

import { useTranslations } from "next-intl";

import { formatRupees } from "@/lib/format";

import type { RepaymentPlan, YearSlice } from "@/lib/emi";
import type { Locale } from "@/i18n/config";

export function RepaymentPlanSheet({
  locale,
  scheme,
  amount,
  rate,
  years,
  moratorium,
  plan,
  schedule,
  generatedAt,
}: {
  locale: Locale;
  /** The scheme the terms were pre-filled from, when there was one. */
  scheme: string | null;
  amount: number;
  rate: number;
  years: number;
  moratorium: number;
  plan: RepaymentPlan;
  schedule: YearSlice[];
  /** Passed in rather than read from the clock here: a `new Date()` during render is the
   *  non-deterministic value scripts/check-hydration.mjs exists to catch. */
  generatedAt: string;
}) {
  const t = useTranslations("calculator");
  const tApp = useTranslations("app");

  // Deliberately not `common.rupees` — see the header comment on the glyph.
  const money = (value: number) => `Rs ${formatRupees(value, locale)}`;

  const parameters = [
    { label: t("amount"), value: money(amount) },
    { label: t("rate"), value: t("ratePercent", { rate }) },
    { label: t("years"), value: t("yearsValue", { count: years }) },
    { label: t("moratorium"), value: t("monthsValue", { count: moratorium }) },
    { label: t("monthlyEmi"), value: money(plan.emi) },
    { label: t("totalInterest"), value: money(plan.totalInterest) },
    { label: t("totalPayment"), value: money(plan.totalPayment) },
  ];

  return (
    <section className="print-only text-ink" aria-hidden="true">
      <header
        className="bg-accent-800 px-8 py-7 text-white"
        style={{ printColorAdjust: "exact", WebkitPrintColorAdjust: "exact" }}
      >
        <p className="font-display text-3xl font-extrabold">{tApp("title")}</p>
        <p className="mt-1.5 text-sm text-white/80">{t("planOrgLine")}</p>
      </header>

      <div className="px-8 py-7">
        <p className="border-b border-line pb-4 font-semibold">{t("planTitle")}</p>

        {scheme && (
          <p className="mt-5 font-semibold text-accent-800" lang="en">
            {t("planScheme", { scheme })}
          </p>
        )}

        <table className="mt-3 w-full border-collapse text-left">
          <thead>
            <tr
              className="bg-accent-800 text-white"
              style={{ printColorAdjust: "exact", WebkitPrintColorAdjust: "exact" }}
            >
              <th scope="col" className="w-1/2 border border-line px-3 py-2">
                {t("colParameter")}
              </th>
              <th scope="col" className="border border-line px-3 py-2">
                {t("colValue")}
              </th>
            </tr>
          </thead>
          <tbody>
            {parameters.map((parameter) => (
              <tr key={parameter.label}>
                <th scope="row" className="border border-line px-3 py-2 font-semibold">
                  {parameter.label}
                </th>
                <td className="numeric border border-line px-3 py-2">{parameter.value}</td>
              </tr>
            ))}
          </tbody>
        </table>

        <table className="mt-7 w-full border-collapse text-left">
          <thead>
            <tr
              className="bg-teal-700 text-white"
              style={{ printColorAdjust: "exact", WebkitPrintColorAdjust: "exact" }}
            >
              <th scope="col" className="border border-line px-3 py-2">
                {t("colYear")}
              </th>
              <th scope="col" className="border border-line px-3 py-2">
                {t("colPrincipalPaid")}
              </th>
              <th scope="col" className="border border-line px-3 py-2">
                {t("colInterestPaid")}
              </th>
              <th scope="col" className="border border-line px-3 py-2">
                {t("colTotalPaid")}
              </th>
            </tr>
          </thead>
          <tbody>
            {schedule.map((slice) => (
              <tr key={slice.year}>
                <th scope="row" className="border border-line px-3 py-2 font-normal">
                  {t("yearLabel", { year: slice.year })}
                </th>
                <td className="numeric border border-line px-3 py-2">
                  {money(slice.principal)}
                </td>
                <td className="numeric border border-line px-3 py-2">
                  {money(slice.interest)}
                </td>
                <td className="numeric border border-line px-3 py-2">
                  {money(slice.principal + slice.interest)}
                </td>
              </tr>
            ))}
          </tbody>
        </table>

        {/* The disclaimer is not a footer flourish. This document has a ministry name at
            the top of it and will be carried into a branch; it has to say on its face
            that it is an estimate and that nobody here approves anything. */}
        <div className="mt-8 border-t border-line pt-4 text-sm text-ink-faint">
          <p>{t("planDisclaimer")}</p>
          <p className="numeric mt-1">{t("generatedAt", { when: generatedAt })}</p>
        </div>
      </div>
    </section>
  );
}
