"""users and console roles

Revision ID: 57c50742b2d2
Revises: 0001
Create Date: 2026-08-30 21:06:27.835940

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import geoalchemy2
import pgvector.sqlalchemy


revision: str = '57c50742b2d2'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('CITIZEN', 'PARTNER', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(role = 'PARTNER' AND partner_id IS NOT NULL) OR (role <> 'PARTNER' AND partner_id IS NULL)", name=op.f('ck_users_partner_role_has_a_partner')),
    sa.ForeignKeyConstraint(['partner_id'], ['channel_partners.id'], name=op.f('fk_users_partner_id_channel_partners'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index('ix_users_partner_id', 'users', ['partner_id'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_partner_id', table_name='users')
    op.drop_table('users')
    # A native enum outlives the table that used it, so a re-upgrade would fail with
    # "type user_role already exists" unless it is dropped here too.
    sa.Enum(name='user_role').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
