"""notifications

Revision ID: 9604dc45523d
Revises: 57c50742b2d2
Create Date: 2026-08-31 18:37:58.832907

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '9604dc45523d'
down_revision: str | None = '57c50742b2d2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('citizen_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.Enum('IN_APP', 'SMS', 'WHATSAPP', 'CONSOLE', name='notification_channel'), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recipient_hint', sa.String(length=4), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'SUPPRESSED', name='notification_status'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('sms_segments', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_notifications_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], name=op.f('fk_notifications_citizen_id_citizens'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_application_id', 'notifications', ['application_id'], unique=False)
    op.create_index('ix_notifications_citizen_id', 'notifications', ['citizen_id'], unique=False)
    op.create_index('ix_notifications_event', 'notifications', ['event'], unique=False)
    op.create_index('ix_notifications_status', 'notifications', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_status', table_name='notifications')
    op.drop_index('ix_notifications_event', table_name='notifications')
    op.drop_index('ix_notifications_citizen_id', table_name='notifications')
    op.drop_index('ix_notifications_application_id', table_name='notifications')
    op.drop_table('notifications')
    # Native enums outlive the table that used them, so a re-upgrade would fail with
    # "type already exists" unless they are dropped here too.
    sa.Enum(name='notification_channel').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='notification_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
