"""initial schema

Creates the full SETU data model: citizen identity and consent, the progressively
collected eligibility profile, the scheme catalogue with provenance columns, versioned
scheme rules, the Channel Partner registry with its scheme-authorisation matrix,
applications and documents, and the two append-only tables (audit_log, match_runs).

Requires the postgis and vector extensions, which scripts/seed/00_extensions.sql
installs on first container start.

Revision ID: 0001
Revises:
Create Date: 2026-08-28

"""
from collections.abc import Sequence

import geoalchemy2
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_table('channel_partners',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('SCA', 'PSB', 'RRB', 'NBFC_MFI', name='partner_type'), nullable=False),
    sa.Column('parent_org', sa.String(length=255), nullable=True),
    sa.Column('ifsc', sa.String(length=11), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('district', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('pincode', sa.String(length=6), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('contact', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("ifsc IS NULL OR ifsc ~ '^[A-Z]{4}0[A-Z0-9]{6}$'", name=op.f('ck_channel_partners_ifsc_is_well_formed')),
    sa.CheckConstraint("pincode IS NULL OR pincode ~ '^[0-9]{6}$'", name=op.f('ck_channel_partners_pincode_is_six_digits')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_partners'))
    )
    op.create_table('consents',
    sa.Column('purpose', sa.String(length=120), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consents'))
    )
    op.create_table('schemes',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('official_name', sa.String(length=255), nullable=False),
    sa.Column('name_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('family', sa.Enum('MICRO_FINANCE', 'TERM_LOAN', 'EDUCATION_LOAN', name='scheme_family'), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('max_funding_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('interest_rate_min', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('interest_rate_max', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('moratorium_months', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('circular_ref', sa.String(length=255), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('last_verified_on', sa.Date(), nullable=True),
    sa.Column('needs_verification', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('interest_rate_min IS NULL OR interest_rate_max IS NULL OR interest_rate_min <= interest_rate_max', name=op.f('ck_schemes_interest_band_is_ordered')),
    sa.CheckConstraint('max_funding_pct IS NULL OR (max_funding_pct > 0 AND max_funding_pct <= 100)', name=op.f('ck_schemes_max_funding_pct_is_a_percentage')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schemes')),
    sa.UniqueConstraint('code', name=op.f('uq_schemes_code'))
    )
    op.create_table('citizens',
    sa.Column('gov_id_type', sa.Enum('AADHAAR', 'PAN', 'VOTER_ID', 'OTHER', name='gov_id_type'), nullable=True),
    sa.Column('gov_id_last4', sa.String(length=4), nullable=True),
    sa.Column('gov_id_hash', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('phone_last4', sa.String(length=4), nullable=True),
    sa.Column('consent_id', sa.UUID(), nullable=False),
    sa.Column('preferred_language', sa.String(length=8), nullable=False),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("gov_id_last4 IS NULL OR gov_id_last4 ~ '^[0-9]{4}$'", name=op.f('ck_citizens_gov_id_last4_is_four_digits')),
    sa.CheckConstraint("phone_last4 IS NULL OR phone_last4 ~ '^[0-9]{4}$'", name=op.f('ck_citizens_phone_last4_is_four_digits')),
    sa.ForeignKeyConstraint(['consent_id'], ['consents.id'], name=op.f('fk_citizens_consent_id_consents'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_citizens')),
    sa.UniqueConstraint('gov_id_hash', name=op.f('uq_citizens_gov_id_hash'))
    )
    op.create_table('partner_scheme_authorisations',
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('scheme_id', sa.UUID(), nullable=False),
    sa.Column('min_ticket', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('max_ticket', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('is_currently_accepting', sa.Boolean(), nullable=False),
    sa.Column('avg_turnaround_days', sa.Integer(), nullable=True),
    sa.Column('active_load', sa.Integer(), nullable=True),
    sa.Column('service_districts', postgresql.ARRAY(sa.String(length=120)), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('active_load IS NULL OR (active_load BETWEEN 0 AND 100)', name=op.f('ck_partner_scheme_authorisations_active_load_is_a_percentage')),
    sa.CheckConstraint('min_ticket IS NULL OR max_ticket IS NULL OR min_ticket <= max_ticket', name=op.f('ck_partner_scheme_authorisations_ticket_band_is_ordered')),
    sa.ForeignKeyConstraint(['partner_id'], ['channel_partners.id'], name=op.f('fk_partner_scheme_authorisations_partner_id_channel_partners'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], name=op.f('fk_partner_scheme_authorisations_scheme_id_schemes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partner_scheme_authorisations')),
    sa.UniqueConstraint('partner_id', 'scheme_id', name='uq_partner_scheme_authorisations_partner_id_scheme_id')
    )
    op.create_table('scheme_rules',
    sa.Column('scheme_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('expression', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('severity', sa.Enum('HARD_BLOCK', 'SOFT_WARN', name='rule_severity'), nullable=False),
    sa.Column('message_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('suggest_instead', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], name=op.f('fk_scheme_rules_scheme_id_schemes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheme_rules')),
    sa.UniqueConstraint('scheme_id', 'rule_id', name='uq_scheme_rules_scheme_id_rule_id')
    )
    op.create_table('citizen_profiles',
    sa.Column('citizen_id', sa.UUID(), nullable=False),
    sa.Column('annual_family_income', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('category', sa.Enum('SC', 'ST', 'OBC', 'GENERAL', name='social_category'), nullable=True),
    sa.Column('sub_category', sa.String(length=120), nullable=True),
    sa.Column('gender', sa.Enum('FEMALE', 'MALE', 'OTHER', 'UNDISCLOSED', name='gender'), nullable=True),
    sa.Column('age', sa.SmallInteger(), nullable=True),
    sa.Column('occupation_type', sa.String(length=120), nullable=True),
    sa.Column('education_level', sa.String(length=120), nullable=True),
    sa.Column('existing_loans', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('project_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('project_sector', sa.String(length=120), nullable=True),
    sa.Column('is_pwd', sa.Boolean(), nullable=True),
    sa.Column('is_safai_karamchari', sa.Boolean(), nullable=True),
    sa.Column('has_caste_certificate', sa.Boolean(), nullable=True),
    sa.Column('admission_confirmed', sa.Boolean(), nullable=True),
    sa.Column('course_start_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('age IS NULL OR (age BETWEEN 0 AND 120)', name=op.f('ck_citizen_profiles_age_within_range')),
    sa.CheckConstraint('annual_family_income IS NULL OR annual_family_income >= 0', name=op.f('ck_citizen_profiles_annual_family_income_non_negative')),
    sa.CheckConstraint('project_cost IS NULL OR project_cost >= 0', name=op.f('ck_citizen_profiles_project_cost_non_negative')),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], name=op.f('fk_citizen_profiles_citizen_id_citizens'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_citizen_profiles')),
    sa.UniqueConstraint('citizen_id', name=op.f('uq_citizen_profiles_citizen_id'))
    )
    op.create_table('match_runs',
    sa.Column('citizen_id', sa.UUID(), nullable=True),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], name=op.f('fk_match_runs_citizen_id_citizens'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_runs'))
    )
    op.create_table('applications',
    sa.Column('citizen_id', sa.UUID(), nullable=False),
    sa.Column('scheme_id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'PARTNER_ACKNOWLEDGED', 'DOCS_REQUESTED', 'UNDER_APPRAISAL', 'SANCTIONED', 'DISBURSED', 'REJECTED', 'WITHDRAWN', name='application_status'), nullable=False),
    sa.Column('amount_requested', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('reference_no', sa.String(length=32), nullable=False),
    sa.Column('match_run_id', sa.UUID(), nullable=True),
    sa.Column('engine_version', sa.String(length=32), nullable=True),
    sa.Column('status_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_requested IS NULL OR amount_requested > 0', name=op.f('ck_applications_amount_requested_is_positive')),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], name=op.f('fk_applications_citizen_id_citizens'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['match_run_id'], ['match_runs.id'], name=op.f('fk_applications_match_run_id_match_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['partner_id'], ['channel_partners.id'], name=op.f('fk_applications_partner_id_channel_partners'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], name=op.f('fk_applications_scheme_id_schemes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications')),
    sa.UniqueConstraint('reference_no', name=op.f('uq_applications_reference_no'))
    )
    op.create_table('documents',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('ocr_extract', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation_status', sa.Enum('PENDING', 'PASSED', 'WARNING', 'FAILED', name='document_validation_status'), nullable=False),
    sa.Column('redaction_applied', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_documents_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index('ix_audit_log_actor', 'audit_log', ['actor'], unique=False)
    op.create_index('ix_audit_log_at', 'audit_log', ['at'], unique=False)
    op.create_index('ix_audit_log_entity_entity_id', 'audit_log', ['entity', 'entity_id'], unique=False)
    op.create_index('ix_channel_partners_district_state', 'channel_partners', ['district', 'state'], unique=False)
    op.create_index('ix_channel_partners_geom', 'channel_partners', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('ix_channel_partners_type_active', 'channel_partners', ['type', 'is_active'], unique=False)
    op.create_index('ix_consents_granted_at', 'consents', ['granted_at'], unique=False)
    op.create_index('ix_schemes_family_active', 'schemes', ['family', 'is_active'], unique=False)
    op.create_index('ix_citizens_district_state', 'citizens', ['district', 'state'], unique=False)
    op.create_index('ix_citizens_geom', 'citizens', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('ix_partner_scheme_authorisations_scheme_accepting', 'partner_scheme_authorisations', ['scheme_id', 'is_currently_accepting'], unique=False)
    op.create_index('ix_partner_scheme_authorisations_service_districts', 'partner_scheme_authorisations', ['service_districts'], unique=False, postgresql_using='gin')
    op.create_index('ix_scheme_rules_severity', 'scheme_rules', ['severity'], unique=False)
    op.create_index('ix_match_runs_at', 'match_runs', ['at'], unique=False)
    op.create_index('ix_match_runs_citizen_id', 'match_runs', ['citizen_id'], unique=False)
    op.create_index('ix_match_runs_engine_version', 'match_runs', ['engine_version'], unique=False)
    op.create_index('ix_applications_citizen_id', 'applications', ['citizen_id'], unique=False)
    op.create_index('ix_applications_partner_status', 'applications', ['partner_id', 'status'], unique=False)
    op.create_index('ix_applications_status', 'applications', ['status'], unique=False)
    op.create_index('ix_documents_application_id', 'documents', ['application_id'], unique=False)
    op.create_index('ix_documents_validation_status', 'documents', ['validation_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_application_id', table_name='documents')
    op.drop_index('ix_documents_validation_status', table_name='documents')
    op.drop_index('ix_applications_citizen_id', table_name='applications')
    op.drop_index('ix_applications_partner_status', table_name='applications')
    op.drop_index('ix_applications_status', table_name='applications')
    op.drop_index('ix_match_runs_at', table_name='match_runs')
    op.drop_index('ix_match_runs_citizen_id', table_name='match_runs')
    op.drop_index('ix_match_runs_engine_version', table_name='match_runs')
    op.drop_index('ix_scheme_rules_severity', table_name='scheme_rules')
    op.drop_index('ix_partner_scheme_authorisations_scheme_accepting', table_name='partner_scheme_authorisations')
    op.drop_index('ix_partner_scheme_authorisations_service_districts', table_name='partner_scheme_authorisations', postgresql_using='gin')
    op.drop_index('ix_citizens_district_state', table_name='citizens')
    op.drop_index('ix_citizens_geom', table_name='citizens', postgresql_using='gist')
    op.drop_index('ix_schemes_family_active', table_name='schemes')
    op.drop_index('ix_consents_granted_at', table_name='consents')
    op.drop_index('ix_channel_partners_district_state', table_name='channel_partners')
    op.drop_index('ix_channel_partners_geom', table_name='channel_partners', postgresql_using='gist')
    op.drop_index('ix_channel_partners_type_active', table_name='channel_partners')
    op.drop_index('ix_audit_log_actor', table_name='audit_log')
    op.drop_index('ix_audit_log_at', table_name='audit_log')
    op.drop_index('ix_audit_log_entity_entity_id', table_name='audit_log')
    op.drop_table('documents')
    op.drop_table('applications')
    op.drop_table('match_runs')
    op.drop_table('citizen_profiles')
    op.drop_table('scheme_rules')
    op.drop_table('partner_scheme_authorisations')
    op.drop_table('citizens')
    op.drop_table('schemes')
    op.drop_table('consents')
    op.drop_table('channel_partners')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
    # Native enum types are not removed by DROP TABLE.
    op.execute('DROP TYPE IF EXISTS partner_type')
    op.execute('DROP TYPE IF EXISTS gov_id_type')
    op.execute('DROP TYPE IF EXISTS social_category')
    op.execute('DROP TYPE IF EXISTS gender')
    op.execute('DROP TYPE IF EXISTS scheme_family')
    op.execute('DROP TYPE IF EXISTS rule_severity')
    op.execute('DROP TYPE IF EXISTS application_status')
    op.execute('DROP TYPE IF EXISTS document_validation_status')
