import { describe, expect, it } from "vitest";

import expected from "../../tests/golden/expected.json";
import type { Profile } from "../src";
import { ENGINE_VERSION, evaluate, nextBestQuestion, run } from "../src";

/**
 * The anti-drift test.
 *
 * `expected.json` is generated by the Python engine. If TypeScript disagrees with it on
 * any case, one of the two runtimes has diverged and a citizen would see a different
 * answer in the browser than the API recorded in match_runs. That must never happen, so
 * this suite fails loudly rather than tolerating "close enough".
 */

const CASES: Record<string, Profile> = {
  empty_profile: {},
  category_only: { category: "SC" },
  sunita_street_vendor_80k: {
    category: "SC",
    project_sector: "TRADE",
    occupation_type: "Vegetable vendor",
    annual_family_income: 180000,
    project_cost: 80000,
  },
  ramesh_workshop_12l: {
    category: "SC",
    project_sector: "MANUFACTURING",
    occupation_type: "Furniture workshop",
    annual_family_income: 420000,
    project_cost: 1200000,
  },
  anjali_student_6l: {
    category: "SC",
    project_sector: "EDUCATION",
    education_level: "Higher secondary",
    admission_confirmed: true,
    annual_family_income: 260000,
    project_cost: 600000,
  },
  income_exactly_at_ceiling: {
    category: "SC",
    project_sector: "SERVICES",
    annual_family_income: 500000,
    project_cost: 100000,
  },
  income_one_rupee_over: {
    category: "SC",
    project_sector: "SERVICES",
    annual_family_income: 500001,
    project_cost: 100000,
  },
  micro_finance_boundary_140000: {
    category: "SC",
    project_sector: "ARTISAN",
    annual_family_income: 200000,
    project_cost: 140000,
  },
  micro_finance_boundary_140001_redirects: {
    category: "SC",
    project_sector: "ARTISAN",
    annual_family_income: 200000,
    project_cost: 140001,
  },
  student_without_confirmed_admission: {
    category: "SC",
    project_sector: "EDUCATION",
    admission_confirmed: false,
    annual_family_income: 260000,
    project_cost: 600000,
  },
  non_sc_applicant: {
    category: "OBC",
    project_sector: "TRADE",
    annual_family_income: 180000,
    project_cost: 80000,
  },
  over_term_loan_ceiling: {
    category: "SC",
    project_sector: "MANUFACTURING",
    annual_family_income: 300000,
    project_cost: 6000000,
  },
};

const golden = expected as unknown as Record<string, Record<string, unknown>>;

describe("conformance with the Python engine", () => {
  it("covers every golden case", () => {
    expect(Object.keys(CASES).sort()).toEqual(Object.keys(golden).sort());
  });

  for (const [name, profile] of Object.entries(CASES)) {
    it(`matches Python for ${name}`, () => {
      expect(JSON.parse(JSON.stringify(run(profile)))).toEqual(golden[name]);
    });
  }
});

describe("engine behaviour", () => {
  it("reports the same engine version as the bundle it was compiled from", () => {
    expect(ENGINE_VERSION).toBe(golden.empty_profile.engine_version);
  });

  it("never treats a missing field as a refusal", () => {
    for (const result of evaluate({})) {
      expect(result.verdict).toBe("NEED_MORE_INFO");
      expect(result.missing_fields.length).toBeGreaterThan(0);
    }
  });

  it("routes the street vendor to micro finance", () => {
    expect(evaluate(CASES.sunita_street_vendor_80k)[0].scheme_code).toBe(
      "NSFDC_MICRO_FINANCE",
    );
  });

  it("redirects an oversized micro finance ask to the term loan", () => {
    const micro = evaluate(CASES.ramesh_workshop_12l).find(
      (r) => r.scheme_code === "NSFDC_MICRO_FINANCE",
    );
    expect(micro?.verdict).toBe("INELIGIBLE");
    expect(micro?.redirect_suggestion).toBe("NSFDC_TERM_LOAN");
  });

  it("asks for category first on an empty profile", () => {
    expect(nextBestQuestion({})?.field).toBe("category");
  });

  it("stops asking once every scheme is decided", () => {
    expect(nextBestQuestion(CASES.sunita_street_vendor_80k)).toBeNull();
  });
});
